INSERT INTO lang_cards (lang_set_id, front, back)
VALUES 
(1, 'Pizza', 'Pizza'),
(1, 'Spaghetti', 'Spaghetti'),
(2, 'Hello', '你好'),
(2, 'Bye', '再見'),
(3, 'Hello', 'こんにちは'),
(3, 'Thank you', 'ありがとう'),
(4, 'Hello', 'Olá'),
(4, 'Please', 'Por favor'),
(5, 'Water', '水'),
(5, 'Hello', '你好'),
(6, 'Hello', '안녕하세요'),
(6, 'Love', '사랑'),
(7, 'Hello', 'Bonjour'),
(7, 'Thank you very much', 'merci beaucoup'),
(8, 'Hello', '¡Hola!'),
(8, 'Goodbye', 'adiós'),
(9, 'Paella', 'Paella'),
(9, 'Tortilla Española', 'Tortilla Española'),
(10, 'To eat', 'Manger'),
(10, 'To drink', 'Boire'),
(11, 'Hello', 'Ciao'),
(11, 'Thank you', 'Grazie'),
(12, 'Hello', 'Olá'),
(12, 'Thank you', 'Obrigado'),
(12, 'How much?', 'Quanto costa?'),
(13, 'Good morning', 'おはようございます'),
(13, 'Excuse me', 'すみません'),
(13, 'Family', 'かぞく'),
(13, 'Nature', 'しぜん'),
(14, 'Greeting', '인사'),
(14, 'Travel', '여행'),
(15, 'Chinese New Year', '新年快樂'),
(15, 'Delicious', '好食'),
(16, 'Milk', '牛奶'),
(16, 'Egg', '雞蛋'),
(16, 'Salt', '鹽'),
(16, 'Sugar', '砂糖');
