INSERT INTO sets (title, description, private, category_id, user_id)
VALUES 
('Algebra Basics', 'Introduction to algebraic concepts.', false, 1, 1),
('Python Essentials', 'Learning Python for beginners.', false, 2, 2),
('Spanish 101', 'Basic Spanish language skills.', false, 3, 3),
('Meditation and Mindfulness', 'Techniques for a peaceful mind.', false, 4, 1),
('Basketball Techniques', 'Improving your basketball skills.', false, 5, 2),
('Modern History', 'An overview of history from the 18th century onwards.', false, 6, 4),
('Impressionist Painters', 'The works of Monet, Degas, and others.', false, 7, 5),
('Physics Fundamentals', 'Basic concepts in physics.', false, 8, 6),
('Guitar Chords', 'Learn the basic guitar chords.', false, 9, 4),
('Shakespeare Plays', 'Study notes on Shakespeare plays.', false, 10, 5),
('Civil War', 'Detailed insights into the American Civil War.', false, 6, 5),
('Renaissance Art', 'Exploring the art of the Renaissance period.', false, 7, 2),
('Basic Chemistry', 'Introduction to chemical elements and reactions.', false, 8, 3),
('Understanding Jazz', 'The history and impact of jazz music.', false, 9, 4),
('British Literature', 'From Chaucer to contemporary writers.', false, 10, 2),
('World War I', 'A study of the Great War events.', false, 6, 3),
('Abstract Art', 'Understanding the abstract art movement.', false, 7, 1),
('Astronomy 101', 'Basics of space, stars, and planets.', false, 8, 2),
('The Beatles', 'The history of the Beatles and their music.', false, 9, 3),
('Poetry Forms', 'Exploring various structures of poetry.', false, 10, 2),
('Biology Basics', 'Introduction to biological concepts and terminologies.', false, 1, 2),
('Python Programming', 'Mastering the basics of Python programming.', false, 2, 3),
('Spanish Verbs', 'Conjugating the most common Spanish verbs.', false, 3, 4),
('Gardening Tips', 'How to maintain a healthy garden.', false, 4, 5),
('Yoga for Beginners', 'Yoga poses and sequences for starters.', false, 5, 4),
('World Literature', 'Exploring literature from around the globe.', false, 1, 3),
('HTML Essentials', 'Learn the basics of web structure with HTML.', false, 2, 4),
('French Vocabulary', 'Building a strong base of French words.', false, 3, 5),
('Knitting Patterns', 'Basic to intermediate knitting patterns.', false, 4, 2),
('Nutrition Fundamentals', 'Understand the basics of good nutrition.', false, 5, 3);
