INSERT INTO cards (set_id, front, back)
VALUES 
(1, 'Solve for x: 2x + 3 = 7', 'x = 2'),
(1, 'What is a quadratic equation?', 'An equation of the form ax^2 + bx + c = 0'),
(2, 'How to define a function in Python?', 'def functionName():'),
(2, 'What is a list comprehension?', 'A concise way to create lists'),
(3, 'How do you say "Hello" in Spanish?', 'Hola'),
(3, 'How do you say "Thank You" in Spanish?', 'Gracias'),
(4, 'What is mindfulness?', 'Paying full attention to the present moment'),
(4, 'A common meditation posture?', 'Lotus position'),
(5, 'What is a dribble in basketball?', 'Bouncing the ball while walking or running'),
(5, 'Name a famous basketball player.', 'Michael Jordan'),
(6, 'Start of the Industrial Revolution', '18th century'),
(6, 'Event marking the end of World War II', 'The surrender of Japan in 1945'),
(7, 'Claude Monet is known for...', 'Water Lilies series and plein air landscape painting'),
(7, 'Edgar Degas was a painter and...', 'Sculptor'),
(8, 'What is the first law of Newton?', 'An object at rest stays at rest and an object in motion stays in motion unless acted upon by a force'),
(8, 'What does E=mc^2 represent?', 'Energy-mass equivalence'),
(9, 'How do you play an E minor chord?', 'Place your index finger on the second fret of the A string and your middle finger on the second fret of the D string'),
(9, 'What is a power chord?', 'A chord that consists of the root note and the fifth'),
(10, 'What is the theme of Macbeth?', 'The corrupting nature of unchecked ambition'),
(10, 'Romeo and Juliet is a tragedy about...', 'Two star-crossed lovers'),
(11, 'Who was the president of the US during the Civil War?', 'Abraham Lincoln'),
(11, 'What year did the Civil War begin?', '1861'),
(12, 'Name a famous Renaissance artist', 'Leonardo da Vinci'),
(12, 'What is the Renaissance known for?', 'Rebirth of art, culture, and intellect started in Italy'),
(13, 'What is the chemical symbol for Gold?', 'Au'),
(13, 'What is the pH of water?', '7 (neutral)'),
(14, 'Who is known as the father of jazz?', 'Louis Armstrong'),
(14, 'What is improvisation in jazz?', 'The act of creating spontaneous music'),
(15, 'Who wrote "1984" and "Animal Farm"?', 'George Orwell'),
(15, 'What is the main theme of "Pride and Prejudice"?', 'Love and social status'),
(16, 'What sparked World War I?', 'The assassination of Archduke Franz Ferdinand of Austria'),
(16, 'What year did World War I end?', '1918'),
(17, 'Name a prominent abstract artist', 'Pablo Picasso'),
(17, 'What is abstract art?', 'Art that does not attempt to represent external reality'),
(18, 'What is the largest planet in our Solar System?', 'Jupiter'),
(18, 'What does a light-year measure?', 'Distance'),
(19, 'What year did The Beatles form?', '1960'),
(19, 'Name a hit song by The Beatles', 'Hey Jude'),
(20, 'Define iambic pentameter', 'A line of verse with five metrical feet, each consisting of one short syllable followed by one long syllable'),
(20, 'Name a poetic device used for the repetition of sounds', 'Alliteration'),
(21, 'What is photosynthesis?', 'The process by which green plants and some other organisms use sunlight to synthesize foods'),
(21, 'What do ribosomes do?', 'They make proteins'),
(22, 'How to declare a variable in Python?', 'Use the `var` keyword, e.g., `var = 5`'),
(22, 'What is a list in Python?', 'A collection which is ordered and changeable, e.g., `myList = [1, 2, 3]`'),
(23, 'How do you conjugate the verb "estar" in present tense?', 'Estoy, estás, está, estamos, estáis, están'),
(23, 'What is the Spanish word for "book"?', 'Libro'),
(24, 'What is the best time to water plants?', 'Early in the morning or late in the afternoon'),
(24, 'What is mulch used for?', 'To retain moisture in the soil, suppress weeds, keep the soil cool'),
(25, 'What is the Sanskrit word for pose in Yoga?', 'Asana'),
(25, 'What is a common breathing technique in Yoga?', 'Pranayama'),
(26, 'Who wrote "One Hundred Years of Solitude"?', 'Gabriel García Márquez'),
(26, 'What is "The Iliad" about?', 'The story of the Trojan War'),
(27, 'What does `<a>` stand for in HTML?', 'Anchor tag, used to define hyperlinks'),
(27, 'What is the purpose of the `<div>` tag in HTML?', 'To define a division or a section in an HTML document'),
(28, 'What is "thank you" in French?', 'Merci'),
(28, 'How do you say "library" in French?', 'Bibliothèque'),
(29, 'What is a purl stitch in knitting?', 'A basic stitch that creates a bumpy texture'),
(29, 'What does "knit two together" mean?', 'A basic decrease stitch in knitting'),
(30, 'What are macronutrients?', 'Nutrients required in large amounts that provide energy: fats, proteins, and carbohydrates'),
(30, 'What is a micronutrient?', 'Vitamins and minerals needed by the body in small amounts');