INSERT INTO lang_cards (lang_set_id, sequence, front, back, image_url)
VALUES 
(1,1, 'Pizza', 'Pizza','https://6ndlkx7fzdluif8n.public.blob.vercel-storage.com/food_pizza_whole-Hz6DvfKdJHqVsH1u0IuHrDvxSaaODW.png'),
(1,2, 'Spaghetti', 'Spaghetti', NULL),
(2,1, 'How are you?','你好嗎？',NULL),
(2,2, 'Good Morning','早上好',NULL),
(2,3, 'Hello','你好',NULL),
(2,4, 'Bye','再見',NULL),
(3,1, 'Hello', 'こんにちは', NULL),
(3,2, 'Thank you', 'ありがとう', NULL),
(4,1, 'Hello', 'Olá', NULL),
(4,2, 'Please', 'Por favor', NULL),
(5,1, 'Water', '水','https://6ndlkx7fzdluif8n.public.blob.vercel-storage.com/water_character-F7IdYbLfwjhtXDxMJn69PdVIVzfnbx.png'),
(5,2, 'Hello', '你好', NULL),
(6,1, 'Hello', '안녕하세요', NULL),
(6,2, 'Love', '사랑', NULL),
(7,1, 'Hello', 'Bonjour', NULL),
(7,2, 'Thank you very much', 'merci beaucoup', NULL),
(8,1, 'Hello', '¡Hola!', NULL),
(8,2, 'Goodbye', 'adiós', NULL),
(9,1, 'Paella', 'Paella', NULL),
(9,2, 'Tortilla Española', 'Tortilla Española', NULL),
(10,1, 'To eat', 'Manger', NULL),
(10,2, 'To drink', 'Boire', NULL),
(11,1, 'Hello', 'Ciao', NULL),
(11,2, 'Thank you', 'Grazie', NULL),
(12,1, 'Hello', 'Olá', NULL),
(12,2, 'Thank you', 'Obrigado', NULL),
(12,3, 'How much?', 'Quanto costa?', NULL),
(13,1, 'Good morning', 'おはようございます', NULL),
(13,2, 'Excuse me', 'すみません', NULL),
(13,3, 'Family', 'かぞく', NULL),
(13,4, 'Nature', 'しぜん', NULL),
(14,1, 'Greeting', '인사', NULL),
(14,2, 'Travel', '여행', NULL),
(15,1, 'Good luck!','祝你好運',NULL),
(15,2, 'Happy Birthday','生日快樂',NULL),
(15,3, 'New Year greetings','恭喜發財',NULL),
(16,1, 'Milk', '牛奶','https://6ndlkx7fzdluif8n.public.blob.vercel-storage.com/drink_milk_pack-Ur3bsAXNGajLE12J9hepZ8Fo0R6sTP.png'),
(16,2, 'Egg', '雞蛋','https://6ndlkx7fzdluif8n.public.blob.vercel-storage.com/egg_yudetamago-mpdTlPWuWz2h5AZ2skLb3XObvjmzPx.png'),
(16,4, 'Salt', '鹽', NULL),
(16,5, 'Sugar', '砂糖', NULL);